// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"time"
)

type Account struct {
	ID              string    `json:"id"`
	Document        string    `json:"document"`
	Balance         int64     `json:"balance"`
	AvailableCredit int64     `json:"available_credit"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
